### PR TITLE
Minor fixes to code

### PR DESCRIPTION
**Pull request by anthonymountain**
Minor changes to fix errors with methods, a few missing brackets caused some errors in code

### CODE REVIEW

**Review by ponyopm — APPROVED** [review]
Pretty simple. No changes to logic, just checkstyle + fixing small errors (missing brackets, etc.).  Nothing wrong.

**Comment by riena42** [comment]
Looking good. No major change no major effect on program. Follows Clean Architecture.

**Review by riena42 — APPROVED** [review]
Already commented.

**Comment by anthonymountain** [comment]
Obsolote changes, I made the changes working with Matteo in his pull request on Monday 11.25.24

**Pull request closed without merging**
